### ISSUE TITLE
This is a test task list

### ISSUE THREAD

**Issue by furgo16** [furgo16/FreeCAD#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

[tasklist]
#### My tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft task

### Full version info

```shell
test
```

### Subproject(s) affected?

Addon Manager

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
